from django.conf.urls import patterns, url

urlpatterns = patterns('movimientos.views',    
    url(r'^$', 'movimientos'),
    #url(r'^datos/$', 'movimientos_datos'),
    url(r'^ventas_lotes/$', 'ventas_de_lotes'),
    url(r'^ventas_lotes/calcular_cuotas/$', 'ventas_de_lotes_calcular_cuotas'),
    url(r'^pago_cuotas/$', 'pago_de_cuotas'),
    url(r'^pago_cuotas_cliente/$', 'pago_de_cuotas_cliente'),
    url(r'^vision_general_cliente/$', 'vision_general_cliente'),
    url(r'^pago_cuotas_venta/(?P<id_venta>\d+)/$', 'pago_de_cuotas_venta'),
    url(r'^calcular_interes/$', 'calcular_interes'),
    url(r'^reservas_lotes/$', 'reservas_de_lotes'),
    url(r'^transferencias_lotes/$', 'transferencias_de_lotes'),
    url(r'^cambio_lotes/$', 'cambio_de_lotes'),
    url(r'^recuperacion_lotes/$', 'recuperacion_de_lotes', name='frontend_recuperacion_lotes'),
    url(r'^eliminar_recuperacion/$', 'eliminar_recuperacion', name='eliminar_recuperacion'),
    url(r'^modificar_pagocuota/(?P<id>\d+)/$', 'modificar_pago_de_cuotas'),
    url(r'^agregar_pago/(?P<id>\d+)/$', 'agregar_pago'),
    url(r'^modificar_venta/(?P<id>\d+)/$', 'modificar_venta'),
    url(r'^eliminar_venta/$', 'eliminar_venta'),
    #url(r'^eliminar_pagocuota/(?P<id>\d+)/$', 'eliminar_pago_de_cuotas'),
    url(r'^listado_ventas/$', 'listar_ventas'),
    url(r'^listado_pagos/$', 'listar_pagos'),
    url(r'^listado_cambios/$', 'listar_cambios'),
    url(r'^listado_recuperacion/$', 'listar_rec'),
    url(r'^listado_reservas/$', 'listar_res'),
    url(r'^listado_transferencias/$', 'listar_transf'),
    url(r'^listado_busqueda_personas/$', 'listar_busqueda_personas'),
    url(r'^listado_busqueda_ventas/$', 'listar_busqueda_ventas'),
    url(r'^listado_busqueda_pagos/$', 'listar_busqueda_pagos'),
    url(r'^listado_busqueda_reservas/$', 'listar_busqueda_reservas'),
    url(r'^listado_busqueda_transferencias/$', 'listar_busqueda_transferencias'),
    url(r'^listado_busqueda_cambios/$', 'listar_busqueda_cambios'),
    url(r'^listado_busqueda_recuperacion/$', 'listar_busqueda_recuperacion'),
    url(r'^eliminar_pagodecuotas/$', 'eliminar_pagodecuotas'),
    url(r'^get_cuotas_a_pagar_by_cliente_id/$', 'get_cuotas_a_pagar_by_cliente_id'),
    url(r'^get_cuotas_a_pagar_by_venta_id_nro_cuotas/$', 'get_cuotas_a_pagar_by_venta_id_nro_cuotas'),
)